import { Movie, Category } from './types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Cyberpunk Chronicles',
    description: 'In a dystopian future where corporations rule the world, a lone hacker uncovers a conspiracy that could shatter reality itself.',
    year: 2024,
    rating: 4.8,
    duration: '2h 15m',
    genre: ['Sci-Fi', 'Action', 'Thriller'],
    posterUrl: 'https://picsum.photos/seed/cyber/300/450',
    bannerUrl: 'https://picsum.photos/seed/cyber/1200/600',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    cast: ['Alex V.', 'Sarah J.', 'Keanu R.'],
    director: 'Ridley S.',
    quality: '4K',
    language: 'English',
    trending: true,
  },
  {
    id: '2',
    title: 'The Last Horizon',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    year: 2023,
    rating: 4.9,
    duration: '2h 45m',
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
    posterUrl: 'https://picsum.photos/seed/space/300/450',
    bannerUrl: 'https://picsum.photos/seed/space/1200/600',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    cast: ['Matt D.', 'Jessica C.', 'Anne H.'],
    director: 'Christopher N.',
    quality: '4K',
    language: 'English',
    trending: true,
  },
  {
    id: '3',
    title: 'Neon Nights',
    description: 'A high-octane racing drama set in the underground streets of Tokyo.',
    year: 2024,
    rating: 4.5,
    duration: '1h 50m',
    genre: ['Action', 'Crime'],
    posterUrl: 'https://picsum.photos/seed/neon/300/450',
    bannerUrl: 'https://picsum.photos/seed/neon/1200/600',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    cast: ['Vin D.', 'Paul W.'],
    director: 'Justin L.',
    quality: 'HD',
    language: 'Japanese',
  },
  {
    id: '4',
    title: 'Ancient Legends',
    description: 'Mythology comes to life when an archaeologist awakens a dormant evil.',
    year: 2022,
    rating: 4.2,
    duration: '2h 10m',
    genre: ['Fantasy', 'Adventure'],
    posterUrl: 'https://picsum.photos/seed/legend/300/450',
    bannerUrl: 'https://picsum.photos/seed/legend/1200/600',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    cast: ['Tom H.', 'Chris H.'],
    director: 'Peter J.',
    quality: '4K',
    language: 'English',
  },
  {
    id: '5',
    title: 'Silent Echo',
    description: 'A psychological thriller about a musician who loses her hearing but starts seeing the future.',
    year: 2024,
    rating: 4.6,
    duration: '1h 55m',
    genre: ['Thriller', 'Drama'],
    posterUrl: 'https://picsum.photos/seed/echo/300/450',
    bannerUrl: 'https://picsum.photos/seed/echo/1200/600',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    cast: ['Natalie P.', 'Jude L.'],
    director: 'Darren A.',
    quality: 'HD',
    language: 'French',
  },
  {
    id: '6',
    title: 'Galactic Wars',
    description: 'The final battle for the galaxy begins now.',
    year: 2023,
    rating: 4.7,
    duration: '2h 30m',
    genre: ['Sci-Fi', 'Action'],
    posterUrl: 'https://picsum.photos/seed/war/300/450',
    bannerUrl: 'https://picsum.photos/seed/war/1200/600',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    cast: ['Daisy R.', 'Adam D.'],
    director: 'J.J. A.',
    quality: '4K',
    language: 'English',
    trending: true,
  }
];

export const CATEGORIES: Category[] = [
  { id: 'trending', name: 'Trending Now', filter: (m) => !!m.trending },
  { id: 'new', name: 'New Releases', filter: (m) => m.year >= 2024 },
  { id: 'action', name: 'Action & Adventure', filter: (m) => m.genre.includes('Action') || m.genre.includes('Adventure') },
  { id: 'scifi', name: 'Sci-Fi & Fantasy', filter: (m) => m.genre.includes('Sci-Fi') || m.genre.includes('Fantasy') },
];